on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - python: '3.10'
          - python: '3.14'
    steps:
    - uses: actions/checkout@v6
    - uses: actions/setup-python@v6
    - run: python3 -m pip install ruff ty coverage
    - run: ruff check xiio.py tests.py
    - run: ty check xiio.py
    - run: python3 -m coverage run -m unittest
    - run: python3 -m coverage report
  publish:
    needs: [test]
    if: startsWith(github.ref, 'refs/tags')
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
    - uses: actions/checkout@v6
    - uses: actions/setup-python@v6
    - run: python3 -m pip install build
    - run: python3 -m build
    - name: publish
      uses: pypa/gh-action-pypi-publish@release/v1
